# Generated by Django 4.2.25 on 2025-10-12 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_age', models.IntegerField(blank=True, null=True)),
                ('model_source', models.CharField(choices=[('online', 'Online AI'), ('offline', 'Offline Template')], default='offline', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('character', models.CharField(blank=True, max_length=100, null=True)),
                ('background', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
