# Generated by Django 4.2.25 on 2025-10-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='key_items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
