# Generated by Django 4.2.26 on 2025-11-23 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_story_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="context_template",
            field=models.CharField(default="5min_basic", max_length=100),
        ),
        migrations.AddField(
            model_name="story",
            name="generation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating_intro", "Generating Intro"),
                    ("intro_ready", "Intro Ready"),
                    ("generating_remaining", "Generating Remaining"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StoryParagraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paragraph_index", models.IntegerField()),
                (
                    "paragraph_type",
                    models.CharField(
                        choices=[
                            ("intro_goal", "Intro Goal"),
                            ("problem_obstacle", "Problem Obstacle"),
                            ("effort_effort", "Effort Effort"),
                            ("climax_climax", "Climax Climax"),
                            ("ending_ending", "Ending Ending"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "tts_audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="audio/paragraphs/"
                    ),
                ),
                ("tts_duration_seconds", models.FloatField(blank=True, null=True)),
                ("is_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "ordering": ["story", "paragraph_index"],
                "unique_together": {("story", "paragraph_index")},
            },
        ),
    ]
